### ISSUE TITLE
Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 6]

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-examples/ansible-blueprint#7]
I saw there was a section for adding .awsconfig items, and looking into if these are a requirement for the example.

Traceback (most recent call last):
  File "/tmp/pip-build-4JYaOO/cloudify-plugins-common/cloudify/dispatch.py", line 600, in main
  File "/tmp/pip-build-4JYaOO/cloudify-plugins-common/cloudify/dispatch.py", line 366, in handle
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/cloudify_aws/ec2/elasticip.py", line 34, in create
    return ElasticIP().create_helper(args)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/cloudify_aws/ec2/elasticip.py", line 191, in __init__
    resource_states=constants.ELASTICIP['STATES']
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/cloudify_aws/base.py", line 280, in __init__
    super(AwsBaseNode, self).__init__(client)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/cloudify_aws/base.py", line 33, in __init__
    client if client else connection.EC2ConnectionClient().client()
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/cloudify_aws/connection.py", line 61, in client
    return EC2Connection(**aws_config)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/auth.py", line 977, in get_auth_handler
    ready_handlers.append(handler(host, config, provider))
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/auth.py", line 301, in __init__
    HmacKeys.__init__(self, host, config, provider)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/auth.py", line 71, in __init__
    self.update_provider(provider)
  File "/opt/mgmtworker/env/plugins/ansible-nodecellar-demo-deploy-v001-aws/lib/python2.7/site-packages/boto/auth.py", line 75, in update_provider
    self._hmac = hmac.new(self._provider.secret_key.encode('utf-8'),
AttributeError: 'dict' object has no attribute 'encode'

**Comment by joshuap-cfy** [comment]
cfy events list --include-logs --execution-id 77394412-9526-4a6c-a402-ffd72da4b190
Listing events for execution id 77394412-9526-4a6c-a402-ffd72da4b190 [include_logs=True]
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> Starting 'install' workflow execution
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v] Creating node
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy] Creating node
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create'
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc'
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq] Creating node
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create'
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc'
2017-04-12T17:47:14 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create'
2017-04-12T17:47:15 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create'
2017-04-12T17:47:15 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode'
2017-04-12T17:47:15 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode'
2017-04-12T17:47:15 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode'
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 1]
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 1]
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 1]
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 1]
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 1]
2017-04-12T17:47:45 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 1]
2017-04-12T17:47:46 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 1]
2017-04-12T17:47:46 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 1]
2017-04-12T17:47:46 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 1]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 2]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 2]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 2]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 2]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 2]
2017-04-12T17:48:16 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 2]
2017-04-12T17:48:17 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 2]
2017-04-12T17:48:17 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 2]
2017-04-12T17:48:17 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 2]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 3]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 3]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 3]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 3]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 3]
2017-04-12T17:48:47 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 3]
2017-04-12T17:48:48 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 3]
2017-04-12T17:48:48 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 3]
2017-04-12T17:48:48 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 3]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 4]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 4]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 4]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 4]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 4]
2017-04-12T17:49:18 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 4]
2017-04-12T17:49:19 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 4]
2017-04-12T17:49:19 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 4]
2017-04-12T17:49:19 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 4]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 5]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 5]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 5]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 5]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 5]
2017-04-12T17:49:49 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 5]
2017-04-12T17:49:50 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 5]
2017-04-12T17:49:50 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 5]
2017-04-12T17:49:50 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 5]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Sending task 'cloudify_aws.ec2.keypair.create' [retry 6]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Sending task 'cloudify_aws.vpc.vpc.create_vpc' [retry 6]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task started 'cloudify_aws.ec2.keypair.create' [retry 6]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task started 'cloudify_aws.vpc.vpc.create_vpc' [retry 6]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Sending task 'cloudify_aws.ec2.elasticip.create' [retry 6]
2017-04-12T17:50:20 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task started 'cloudify_aws.ec2.elasticip.create' [retry 6]
2017-04-12T17:50:21 CFY <ansible-nodecellar-demo-deploy-v001> [key_gj6k7v.create] Task failed 'cloudify_aws.ec2.keypair.create' -> 'dict' object has no attribute 'encode' [retry 6]
2017-04-12T17:50:21 CFY <ansible-nodecellar-demo-deploy-v001> [vpc_p3dkwy.create] Task failed 'cloudify_aws.vpc.vpc.create_vpc' -> 'dict' object has no attribute 'encode' [retry 6]
2017-04-12T17:50:21 CFY <ansible-nodecellar-demo-deploy-v001> [application_ip_cquttq.create] Task failed 'cloudify_aws.ec2.elasticip.create' -> 'dict' object has no attribute 'encode' [retry 6]
2017-04-12T17:50:24 CFY <ansible-nodecellar-demo-deploy-v001> 'install' workflow execution cancelled

Total events: 68

**Comment by joshuap-cfy** [comment]
Here is the blueprint that I'm using and slightly modified:

(342) [centos@cfy342-cli ansible-blueprint]$ cat aws-ansible-blueprint.yaml
tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.0/types.yaml
  - http://getcloudify.org.s3.amazonaws.com/spec/aws-plugin/1.4.4/plugin.yaml
  - http://www.getcloudify.org/spec/diamond-plugin/1.3.5/plugin.yaml
  - types/aws-ansible-types.yaml

#####################################################################################
# inputs section allows the user to use same
# blueprint for creating different deployments, each one
# with its own parameters.
# to specify deployment inputs run:
#   - cfy deployments create -b <blueprint_id> -d <deployment_id> -i inputs.json
#####################################################################################

inputs:

  key_name:
    default: demo_cfy_instance_keypair.pem

  private_key_path:
    default: ~/.ssh/demo_cfy_instance_keypair.pem

  vpc_id:
    type: string

  vpc_cidr_block:
    type: string

  subnet_id:
    type: string

  subnet_cidr:
    type: string

  ec2_region_name:
    default: us-west-2

  ec2_region_endpoint:
    default: ec2.us-west-2.amazonaws.com

  availability_zone:
    default: us-west-2a

  ami:
    description: >
      Amazon Ubuntu 14.04 AMI

  instance_type:
    description: >
      Agent VM Instance Type

  agent_user:
    default: ubuntu

dsl_definitions:

    aws_config: &aws_config
      aws_access_key_id: { get_secret: aws_access_key_id }
      aws_secret_access_key: { get_secret: aws_secret_access_key }
      ec2_region_name: { get_input: ec2_region_name }
      ec2_region_endpoint: { get_input: ec2_region_endpoint }

node_templates:

  ansible:
    type: ansible.nodes.Ansible
    properties:
      playbook_file_name: main.yaml
      public_ip: { get_attribute: [application_ip, aws_resource_id] }
    relationships:
      - type: ansible.relationships.contained_in
        target: application_host

  mongod:
    type: ansible.nodes.MongoDatabase
    properties:
      public_ip: { get_attribute: [application_ip, aws_resource_id] }
    relationships:
      - type: cloudify.relationships.contained_in
        target: application_host
      - type: ansible.relationships.provisioned_by
        target: ansible

  nodejs:
    type: ansible.nodes.NodecellarApplicationModule
    properties:
      public_ip: { get_attribute: [application_ip, aws_resource_id] }
    relationships:
      - type: cloudify.relationships.contained_in
        target: application_host
      - type: ansible.relationships.provisioned_by
        target: ansible
      - type: node_connected_to_mongo
        target: mongod

  application_host:
    type: cloudify.aws.nodes.Instance
    properties:
      agent_config:
        install_method: remote
        port: 22
        user: { get_input: agent_user }
        key: { get_property: [ key, private_key_path ] }
      aws_config: *aws_config
      image_id: { get_input: ami }
      instance_type: { get_input: instance_type }
      parameters:
          placement: { get_property: [ subnet, availability_zone ] }
    relationships:
      - type: cloudify.aws.relationships.instance_connected_to_keypair
        target: key
      - type: cloudify.aws.relationships.instance_connected_to_elastic_ip
        target: application_ip
      - type: cloudify.aws.relationships.instance_connected_to_subnet
        target: subnet
      - type: cloudify.aws.relationships.instance_connected_to_security_group
        target: application_security_group

  application_security_group:
    type: cloudify.aws.nodes.SecurityGroup
    properties:
      aws_config: *aws_config
      description: Security Group for ansible VMs
      rules:
        - ip_protocol: tcp
          from_port: 22
          to_port: 22
          cidr_ip: { get_input: vpc_cidr_block }
        - ip_protocol: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - ip_protocol: tcp
          from_port: 27017
          to_port: 27017
          cidr_ip: { get_input: vpc_cidr_block }
    relationships:
      - type: cloudify.aws.relationships.security_group_contained_in_vpc
        target: vpc

  subnet:
    type: cloudify.aws.nodes.Subnet
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: { get_input: subnet_id }
      cidr_block: { get_input: subnet_cidr }
      availability_zone: { get_input: availability_zone }
    relationships:
      - type: cloudify.aws.relationships.subnet_contained_in_vpc
        target: vpc

  application_ip:
    type: cloudify.aws.nodes.ElasticIP
    properties:
      aws_config: *aws_config
      domain: vpc

  vpc:
    type: cloudify.aws.nodes.VPC
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: { get_input: vpc_id }
      cidr_block: { get_input: vpc_cidr_block }

  key:
    type: cloudify.aws.nodes.KeyPair
    properties:
      aws_config: *aws_config
      resource_id: { get_input: key_name }
      private_key_path: { get_input: private_key_path }

###########################################################
# This outputs section exposes the application endpoint.
# You can access it by running:
#   - cfy deployments -d <deployment_id> outputs
###########################################################

outputs:
  endpoint:
    description: Web application endpoint
    value:
      ip_address: { get_attribute: [ application_ip, aws_resource_id ] }
      port: 8080

**Comment by joshuap-cfy** [comment]
(342) [centos@cfy342-cli ansible-blueprint]$ cat inputs/aws-ansible-blueprint-inputs.yaml
vpc_id: vpc-1fe66d78
vpc_cidr_block: 172.30.0.0/16
subnet_id: subnet-5c0fa33b
subnet_cidr: 172.30.0.0/24
ec2_region_name: us-west-2
ec2_region_endpoint: ec2.us-west-2.amazonaws.com
availability_zone: us-west-2a
ami: ami-d2c924b2
instance_type: t2.large
